# fly.toml app configuration file generated for bold-shape-1507 on 2023-10-21T10:14:07+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-shape-1507"
primary_region = "syd"

[build]

[env]
  PORT = "3000"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
